USERNAME = ''
PASSWORD = ''
API_KEY = ''
TIMEZONE = 8

SMTP_SERVER = ''
SMTP_SERVER_PORT = 25
EMAIL_ACCOUNT = ''
EMAIL_PASSWORD = ''
EMAIL_ADDRESS = ''
FORWARD_ADDRESS = ''

IGNORE_PRIVATE_PLURKS = true

BASE_URL = 'http://www.plurk.com/API'
PLURK_BASE_URL = 'http://www.plurk.com/p/'

DISPLAY_NAME_COLOR = '36'
CONTENT_COLOR = '32'
ORIGINAL_CONTENT_COLOR = '33'
ORIGINAL_NAME_COLOR = '31'
