USERNAME = ''
PASSWORD = ''
API_KEY = ''
TIMEZONE = 8

SMTP_SERVER = 'smtp.gmail.com'
SMTP_SERVER_PORT = 587
EMAIL_ACCOUNT = ''
EMAIL_PASSWORD = ''
EMAIL_ADDRESS = ''
FORWARD_ADDRESS = ''

IGNORE_PRIVATE_PLURKS = true

BASE_URL = 'http://www.plurk.com/API'
PLURK_BASE_URL = 'http://www.plurk.com/p/'

LOGIN = 0
GET_PLURKS = 1
GET_RESPONSE = 2
GET_PUBLIC_PROFILE = 3
